"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Hash, Heart, LoaderCircle, Pencil, Plus, ReceiptText, Trash2, X } from "lucide-react";
import { deleteFavorite, listCategories, listCurrencies, listFavorites, listTags, saveFavorite, toggleFavorite } from "@/lib/data";
import { formatMoney } from "@/lib/analytics";
import type { Category, EnabledCurrency, FavoriteInput, FavoriteTemplate, Tag } from "@/types/domain";
import { StatusMessage } from "./status-message";

type FavoriteDraft = FavoriteInput;
const emptyDraft = (): FavoriteDraft => ({ item_name: "", default_amount: 0, currency_code: "TWD", category_id: "", note: "", default_exchange_rate_to_twd: 1, sort_order: 0, tag_ids: [] });

export function FavoritesManager() {
  const router = useRouter(); const [favorites, setFavorites] = useState<FavoriteTemplate[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [currencies, setCurrencies] = useState<EnabledCurrency[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [draft, setDraft] = useState<FavoriteDraft>(emptyDraft); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const [f, c, u, t] = await Promise.all([listFavorites(true), listCategories(true), listCurrencies(true), listTags(true)]); setFavorites(f); setCategories(c); setCurrencies(u); setTags(t); } catch { setError("無法載入常用項目。" ); } finally { setLoading(false); } }
  useEffect(() => { Promise.all([listFavorites(true), listCategories(true), listCurrencies(true), listTags(true)]).then(([f, c, u, t]) => { setFavorites(f); setCategories(c); setCurrencies(u); setTags(t); }).catch(() => setError("無法載入常用項目。" )).finally(() => setLoading(false)); }, []);
  function openNew() { const category = categories.find((c) => c.is_active); setDraft({ ...emptyDraft(), category_id: category?.id ?? "" }); setEditingId(null); setShowForm(true); setError(""); }
  function openEdit(f: FavoriteTemplate) { setDraft({ item_name: f.item_name, default_amount: f.default_amount, currency_code: f.currency_code, category_id: f.category_id, note: f.note, default_exchange_rate_to_twd: f.default_exchange_rate_to_twd, sort_order: f.sort_order, tag_ids: f.tags?.map((tag) => tag.id) ?? [] }); setEditingId(f.id); setShowForm(true); setError(""); }
  function update<K extends keyof FavoriteDraft>(key: K, value: FavoriteDraft[K]) { setDraft((old) => ({ ...old, [key]: value, ...(key === "currency_code" && value === "TWD" ? { default_exchange_rate_to_twd: 1 } : {}) })); }
  function toggleTag(tagId: string) { setDraft((old) => ({ ...old, tag_ids: old.tag_ids.includes(tagId) ? old.tag_ids.filter((id) => id !== tagId) : [...old.tag_ids, tagId] })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { if (!draft.item_name.trim() || !draft.category_id || draft.default_amount <= 0 || draft.default_exchange_rate_to_twd <= 0) throw new Error("請填寫所有必填欄位，金額與匯率需大於 0。" ); await saveFavorite(draft, editingId ?? undefined); setShowForm(false); setMessage(editingId ? "常用項目已更新。" : "常用項目已建立。" ); await load(); } catch (cause) { const detail = cause instanceof Error ? cause.message : ""; setError(detail.includes("UNIQUE") || detail.includes("duplicate") ? "這個項目名稱已經是常用項目。" : detail || "無法儲存常用項目。" ); } finally { setSaving(false); } }
  async function remove(f: FavoriteTemplate) { if (!window.confirm(`確定刪除常用項目「${f.item_name}」？`)) return; try { await deleteFavorite(f.id); setMessage("常用項目已刪除。" ); await load(); } catch { setError("無法刪除常用項目。" ); } }
  async function setFavoriteState(f: FavoriteTemplate) { setBusy(f.id); setError(""); try { await toggleFavorite(f.id, !f.is_active); setMessage(f.is_active ? "常用項目已停用；既有資料不受影響。" : "常用項目已啟用。" ); await load(); } catch { setError("無法更新常用項目。" ); } finally { setBusy(""); } }
  function startFromFavorite(id: string) { sessionStorage.setItem("favoriteToLoad", id); router.push("/app"); }
  const activeCategories = categories.filter((c) => c.is_active || c.id === draft.category_id); const activeCurrencies = currencies.filter((c) => c.is_active || c.code === draft.currency_code);
  if (loading) return <div className="card flex min-h-48 items-center justify-center"><LoaderCircle className="animate-spin text-moss-600" /></div>;
  return <div className="space-y-5">
    <div className="flex justify-end"><button className="btn-primary" onClick={openNew} disabled={!categories.some((c) => c.is_active)}><Plus size={18} />新增常用項目</button></div>
    {!categories.some((c) => c.is_active) && <StatusMessage message="請先到設定建立並啟用至少一個分類。" error />}
    <StatusMessage message={error || message} error={Boolean(error)} />
    {favorites.length === 0 ? <section className="card py-14 text-center"><Heart className="mx-auto mb-4 text-coral" size={38} /><h2 className="text-lg font-bold">還沒有常用項目</h2><p className="mt-2 text-stone-500">把經常出現的支出存成常用項目，下次只需確認與微調。</p></section> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{favorites.map((f) => <article key={f.id} className={`card flex flex-col ${f.is_active ? "" : "opacity-65"}`}><div className="flex items-start gap-3"><div className="rounded-2xl bg-red-50 p-2.5 text-coral"><Heart size={20} fill="currentColor" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="min-w-0 flex-1 truncate font-bold">{f.item_name}</h2><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-medium ${f.is_active ? "bg-moss-100 text-moss-700" : "bg-stone-100 text-stone-500"}`}>{f.is_active ? "已啟用" : "已停用"}</span></div><p className="truncate text-sm text-stone-500">{f.categories?.name} · {f.currency_code}</p></div></div><p className="mt-5 text-2xl font-bold">{formatMoney(f.default_amount, f.currency_code)}</p>{f.currency_code !== "TWD" && <p className="mt-1 text-xs text-stone-400">預設匯率 {f.default_exchange_rate_to_twd}</p>}{Boolean(f.tags?.length) && <div className="mt-3 flex flex-wrap gap-1.5">{f.tags?.map((tag) => <span key={tag.id} className="rounded-full bg-moss-100 px-2.5 py-1 text-xs text-moss-700">#{tag.name}</span>)}</div>}<p className="mt-3 line-clamp-2 min-h-10 text-sm text-stone-500">{f.note || "沒有備註"}</p><div className="mt-5 flex flex-wrap gap-2"><button className="btn-primary min-w-36 flex-1 px-3" disabled={!f.is_active || busy === f.id} onClick={() => startFromFavorite(f.id)}><ReceiptText size={17} />用這個記帳</button><button className="btn-secondary px-3 text-sm" disabled={busy === f.id} onClick={() => setFavoriteState(f)}>{f.is_active ? "停用" : "啟用"}</button><button className="btn-secondary px-3" aria-label="編輯" disabled={busy === f.id} onClick={() => openEdit(f)}><Pencil size={17} /></button><button className="btn-secondary px-3 text-red-600" aria-label="刪除" disabled={busy === f.id} onClick={() => remove(f)}><Trash2 size={17} /></button></div></article>)}</section>}
    {showForm && <div className="fixed inset-0 z-50 overflow-y-auto bg-ink/40 p-4 backdrop-blur-sm"><form onSubmit={submit} className="card mx-auto my-4 max-w-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{editingId ? "編輯常用項目" : "新增常用項目"}</h2><button type="button" className="rounded-xl p-2 hover:bg-stone-100" onClick={() => setShowForm(false)}><X /></button></div><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">項目名稱 *</label><input className="field" required maxLength={100} value={draft.item_name} onChange={(e) => update("item_name", e.target.value)} placeholder="同一名稱只能建立一個常用項目" /></div><div><label className="label">預設金額 *</label><input className="field" type="number" min="0.0001" step="0.0001" required value={draft.default_amount || ""} onChange={(e) => update("default_amount", Number(e.target.value))} /></div><div><label className="label">幣別 *</label><select className="field" value={draft.currency_code} onChange={(e) => update("currency_code", e.target.value)}>{activeCurrencies.map((c) => <option key={c.code} value={c.code}>{c.code}</option>)}</select></div><div><label className="label">分類 *</label><select className="field" required value={draft.category_id} onChange={(e) => update("category_id", e.target.value)}>{activeCategories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{draft.currency_code !== "TWD" && <div><label className="label">預設換算 TWD 匯率 *</label><input className="field" type="number" min="0.00000001" step="0.00000001" required value={draft.default_exchange_rate_to_twd || ""} onChange={(e) => update("default_exchange_rate_to_twd", Number(e.target.value))} /></div>}<div className="sm:col-span-2"><label className="label">預設備註（選填）</label><textarea className="field min-h-24" maxLength={500} value={draft.note} onChange={(e) => update("note", e.target.value)} /></div><div className="sm:col-span-2"><div className="mb-2 flex items-center gap-2"><Hash size={16} className="text-coral" /><span className="label mb-0">預設 Tag（選填，可複選）</span></div>{tags.length ? <div className="flex flex-wrap gap-2">{tags.map((tag) => { const selected = draft.tag_ids.includes(tag.id); return <button key={tag.id} type="button" aria-pressed={selected} onClick={() => toggleTag(tag.id)} className={`rounded-full border px-3 py-1.5 text-sm transition ${selected ? "border-moss-500 bg-moss-100 text-moss-700" : "border-stone-200 bg-stone-50 text-stone-500 hover:border-moss-500"}`}>#{tag.name}</button>; })}</div> : <p className="text-sm text-stone-400">尚未建立 Tag，可到設定頁新增。</p>}</div></div><StatusMessage message={error} error /><button className="btn-primary mt-5 w-full sm:w-auto" disabled={saving}>{saving ? <LoaderCircle className="animate-spin" size={18} /> : <Heart size={18} />}儲存常用項目</button></form></div>}
  </div>;
}
