"use client";

import { useEffect, useState, type ReactNode } from "react";
import { closestCenter, DndContext, KeyboardSensor, PointerSensor, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { arrayMove, SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Check, GripVertical, LoaderCircle, Pencil, Plus, Tags, Trash2, X } from "lucide-react";
import { CURRENCY_NAMES, ISO_CURRENCIES } from "@/lib/constants";
import { deleteCategory, deleteTag, listCategories, listCurrencies, listTags, reorderCategories, reorderTags, saveCategory, saveTag, toggleCategory, toggleCurrency } from "@/lib/data";
import { categoryNameSchema, exchangeRateSchema, tagNameSchema } from "@/lib/validation";
import type { Category, EnabledCurrency, Tag } from "@/types/domain";
import { StatusMessage } from "./status-message";

export function reorderById<T extends { id: string }>(items: T[], activeId: string, overId: string) {
  const oldIndex = items.findIndex((item) => item.id === activeId); const newIndex = items.findIndex((item) => item.id === overId);
  return oldIndex < 0 || newIndex < 0 || oldIndex === newIndex ? items : arrayMove(items, oldIndex, newIndex);
}

function SortableRow({ children, disabled, id, label }: { children: ReactNode; disabled: boolean; id: string; label: string }) {
  const { attributes, isDragging, listeners, setNodeRef, transform, transition } = useSortable({ id, disabled });
  return <div ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition, zIndex: isDragging ? 10 : undefined }} className={`flex items-center gap-2 py-3 ${isDragging ? "relative rounded-xl bg-stone-100 px-2 shadow-lg" : ""}`}><button type="button" className="shrink-0 cursor-grab touch-none rounded-lg p-2 text-stone-400 hover:bg-stone-100 active:cursor-grabbing disabled:cursor-not-allowed disabled:opacity-40" aria-label={`拖拉排序${label}`} disabled={disabled} {...attributes} {...listeners}><GripVertical size={18} /></button>{children}</div>;
}

export function SettingsManager() {
  const [categories, setCategories] = useState<Category[]>([]); const [currencies, setCurrencies] = useState<EnabledCurrency[]>([]); const [currencyRates, setCurrencyRates] = useState<Record<string, string>>({}); const [tags, setTags] = useState<Tag[]>([]); const [name, setName] = useState(""); const [tagName, setTagName] = useState(""); const [editing, setEditing] = useState<Category | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  function setLoadedCurrencies(rows: EnabledCurrency[]) { setCurrencies(rows); setCurrencyRates(Object.fromEntries(rows.map((currency) => [currency.code, String(currency.default_exchange_rate_to_twd)]))); }
  async function load() { setLoading(true); try { const [c, u, t] = await Promise.all([listCategories(true), listCurrencies(true), listTags()]); setCategories(c); setLoadedCurrencies(u); setTags(t); } catch { setError("無法載入設定。" ); } finally { setLoading(false); } }
  useEffect(() => { Promise.all([listCategories(true), listCurrencies(true), listTags()]).then(([c, u, t]) => { setCategories(c); setLoadedCurrencies(u); setTags(t); }).catch(() => setError("無法載入設定。" )).finally(() => setLoading(false)); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); try { const valid = categoryNameSchema.parse(editing ? editing.name : name); await saveCategory(valid, editing?.id); setName(""); setEditing(null); setMessage(editing ? "分類已重新命名。" : "分類已建立。" ); await load(); } catch (cause) { setError(cause instanceof Error && cause.message.startsWith("[") ? "請輸入 1 至 40 字的分類名稱。" : "分類名稱可能重複，請使用其他名稱。" ); } }
  async function setCategoryState(c: Category) { setBusy(c.id); setError(""); try { await toggleCategory(c.id, !c.is_active); setMessage(c.is_active ? "分類已停用，歷史帳目不受影響。" : "分類已啟用。" ); await load(); } catch { setError("無法更新分類。" ); } finally { setBusy(""); } }
  async function remove(c: Category) { if (!window.confirm(`刪除未使用的分類「${c.name}」？`)) return; setBusy(c.id); try { await deleteCategory(c.id); setMessage("分類已刪除。" ); await load(); } catch { setError("此分類已被帳目或常用項目使用，請改為停用。" ); } finally { setBusy(""); } }
  async function finishCategoryDrag(event: DragEndEvent) { if (!event.over || event.active.id === event.over.id) return; const previous = categories; const next = reorderById(categories, String(event.active.id), String(event.over.id)); if (next === categories) return; setCategories(next); setBusy("category-order"); setError(""); try { await reorderCategories(next.map((category) => category.id)); setMessage("分類順序已更新。" ); } catch { setCategories(previous); setError("無法更新分類順序。" ); } finally { setBusy(""); } }
  async function setCurrency(code: string, active: boolean) { if (code === "TWD") return; const current = currencies.find((currency) => currency.code === code); const parsedRate = active ? exchangeRateSchema.safeParse(currencyRates[code]) : null; if (active && !parsedRate?.success) { setError(`請為 ${code} 輸入大於 0 的有效預設匯率。` ); return; } const rate = parsedRate?.success ? parsedRate.data : current?.default_exchange_rate_to_twd ?? 1; setBusy(code); setError(""); try { await toggleCurrency(code, active, rate); setMessage(active ? (current?.is_active ? `${code} 預設匯率已儲存。` : `${code} 已啟用並儲存預設匯率。`) : `${code} 已停用，歷史帳目不受影響。`); await load(); } catch { setError("無法更新幣別，請稍後再試。" ); } finally { setBusy(""); } }
  async function submitTag(event: React.FormEvent) { event.preventDefault(); setError(""); try { const valid = tagNameSchema.parse(tagName); await saveTag(valid); setTagName(""); setMessage("Tag 已建立。" ); await load(); } catch (cause) { setError(cause instanceof Error && cause.message.startsWith("[") ? "請輸入 1 至 30 字的 Tag 名稱。" : "Tag 名稱可能重複，請使用其他名稱。" ); } }
  async function removeTag(tag: Tag) { if (!window.confirm(`刪除 Tag「${tag.name}」？帳目本身不會被刪除。`)) return; setBusy(tag.id); try { await deleteTag(tag.id); setMessage("Tag 已刪除，原帳目不受影響。" ); await load(); } catch { setError("無法刪除 Tag。" ); } finally { setBusy(""); } }
  async function finishTagDrag(event: DragEndEvent) { if (!event.over || event.active.id === event.over.id) return; const previous = tags; const next = reorderById(tags, String(event.active.id), String(event.over.id)); if (next === tags) return; setTags(next); setBusy("tag-order"); setError(""); try { await reorderTags(next.map((tag) => tag.id)); setMessage("Tag 順序已更新。" ); } catch { setTags(previous); setError("無法更新 Tag 順序。" ); } finally { setBusy(""); } }
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  const currencyMap = new Map(currencies.map((c) => [c.code, c]));
  if (loading) return <div className="card flex min-h-48 items-center justify-center"><LoaderCircle className="animate-spin text-moss-600" /></div>;
  return <div className="grid gap-5 lg:grid-cols-2">
    <section className="card"><h2 className="text-lg font-bold">支出分類</h2><p className="muted mt-1">按住左側把手即可拖拉排序；使用過的分類請停用而非刪除。</p><form onSubmit={submit} className="mt-5 flex gap-2">{editing ? <input className="field" aria-label="分類名稱" value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /> : <input className="field" aria-label="新分類名稱" value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：餐飲" />}<button className="btn-primary shrink-0">{editing ? <Check size={18} /> : <Plus size={18} />}<span className="hidden sm:inline">{editing ? "儲存" : "新增"}</span></button>{editing && <button type="button" className="btn-secondary px-3" onClick={() => setEditing(null)}><X size={18} /></button>}</form><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={(event) => void finishCategoryDrag(event)}><SortableContext items={categories.map((category) => category.id)} strategy={verticalListSortingStrategy}><div className="mt-5 divide-y divide-stone-100">{categories.length === 0 && <p className="py-8 text-center text-stone-400">還沒有分類，先建立第一個吧</p>}{categories.map((c) => <SortableRow key={c.id} id={c.id} label={`分類 ${c.name}`} disabled={busy === "category-order"}><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${c.is_active ? "bg-moss-500" : "bg-stone-300"}`} /><span className="min-w-0 flex-1 truncate font-medium">{c.name}</span><button type="button" className="rounded-xl p-2 text-stone-400 hover:bg-stone-100" aria-label={`重新命名分類 ${c.name}`} onClick={() => setEditing(c)}><Pencil size={17} /></button><button type="button" className="rounded-xl p-2 text-stone-400 hover:bg-red-50 hover:text-red-700" aria-label={`刪除分類 ${c.name}`} disabled={busy === c.id} onClick={() => remove(c)}><Trash2 size={17} /></button><button type="button" className="btn-secondary min-h-9 px-3 py-1 text-sm" disabled={busy === c.id} onClick={() => setCategoryState(c)}>{c.is_active ? "停用" : "啟用"}</button></SortableRow>)}</div></SortableContext></DndContext></section>
    <section className="card"><div className="flex items-center gap-2"><Tags size={20} className="text-coral" /><h2 className="text-lg font-bold">帳目 Tag</h2></div><p className="muted mt-1">Tag 是選填，可讓同一筆帳目同時擁有多個標籤；按住左側把手即可拖拉排序。</p><form onSubmit={submitTag} className="mt-5 flex gap-2"><input className="field" aria-label="新 Tag 名稱" value={tagName} onChange={(e) => setTagName(e.target.value)} placeholder="例如：出差" maxLength={30} /><button className="btn-primary shrink-0"><Plus size={18} /><span className="hidden sm:inline">新增</span></button></form><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={(event) => void finishTagDrag(event)}><SortableContext items={tags.map((tag) => tag.id)} strategy={verticalListSortingStrategy}><div className="mt-5 divide-y divide-stone-100">{tags.length === 0 && <p className="py-8 text-center text-stone-400">尚未建立 Tag</p>}{tags.map((tag) => <SortableRow key={tag.id} id={tag.id} label={`Tag ${tag.name}`} disabled={busy === "tag-order"}><span className="min-w-0 flex-1 truncate font-medium">#{tag.name}</span><button type="button" className="rounded-xl p-2 text-stone-400 hover:bg-red-50 hover:text-red-700" aria-label={`刪除 Tag ${tag.name}`} disabled={busy === tag.id} onClick={() => removeTag(tag)}><Trash2 size={17} /></button></SortableRow>)}</div></SortableContext></DndContext></section>
    <section className="card"><h2 className="text-lg font-bold">使用幣別</h2><p className="muted mt-1">啟用外幣時設定預設匯率；新增帳目選到該幣別會自動帶入，單筆仍可修改。</p><div className="mt-5 max-h-[32rem] divide-y divide-stone-100 overflow-y-auto">{ISO_CURRENCIES.map(([code]) => { const currency = currencyMap.get(code); const active = code === "TWD" || Boolean(currency?.is_active); return <div key={code} className="py-3"><div className="flex items-center gap-3"><span className="w-12 font-mono font-bold">{code}</span><span className="min-w-0 flex-1 text-sm text-stone-500">{CURRENCY_NAMES[code]}</span><span className={`rounded-full px-3 py-1 text-xs font-medium ${active ? "bg-moss-100 text-moss-700" : "bg-stone-100 text-stone-500"}`}>{active ? "已啟用" : "未啟用"}</span></div>{code === "TWD" ? <p className="mt-2 text-sm text-stone-400">1 TWD = 1 TWD（固定）</p> : <div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-center"><label className="text-sm text-stone-500" htmlFor={`currency-rate-${code}`}>1 {code} =</label><input className="field min-h-10 px-3 py-2 sm:w-40" id={`currency-rate-${code}`} aria-label={`${code} 預設匯率`} type="number" min="0.00000001" step="0.00000001" inputMode="decimal" value={currencyRates[code] ?? ""} onChange={(event) => setCurrencyRates((old) => ({ ...old, [code]: event.target.value }))} placeholder="輸入匯率" /><span className="text-sm text-stone-500">TWD</span><button type="button" className="btn-primary min-h-10 px-3 py-2 text-sm" disabled={busy === code} onClick={() => setCurrency(code, true)}>{active ? "儲存" : "啟用"}</button>{active && <button type="button" className="btn-secondary min-h-10 px-3 py-2 text-sm" disabled={busy === code} onClick={() => setCurrency(code, false)}>停用</button>}</div>}</div>; })}</div></section>
    <div className="lg:col-span-2"><StatusMessage message={error || message} error={Boolean(error)} /></div>
  </div>;
}
