"use client";

import { useEffect, useState } from "react";
import { Check, LoaderCircle, Pencil, Plus, Tags, Trash2, X } from "lucide-react";
import { CURRENCY_NAMES, ISO_CURRENCIES } from "@/lib/constants";
import { deleteCategory, deleteTag, listCategories, listCurrencies, listTags, saveCategory, saveTag, toggleCategory, toggleCurrency } from "@/lib/data";
import { categoryNameSchema, tagNameSchema } from "@/lib/validation";
import type { Category, EnabledCurrency, Tag } from "@/types/domain";
import { StatusMessage } from "./status-message";

export function SettingsManager() {
  const [categories, setCategories] = useState<Category[]>([]); const [currencies, setCurrencies] = useState<EnabledCurrency[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [name, setName] = useState(""); const [tagName, setTagName] = useState(""); const [editing, setEditing] = useState<Category | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const [c, u, t] = await Promise.all([listCategories(true), listCurrencies(true), listTags()]); setCategories(c); setCurrencies(u); setTags(t); } catch { setError("無法載入設定。" ); } finally { setLoading(false); } }
  useEffect(() => { Promise.all([listCategories(true), listCurrencies(true), listTags()]).then(([c, u, t]) => { setCategories(c); setCurrencies(u); setTags(t); }).catch(() => setError("無法載入設定。" )).finally(() => setLoading(false)); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); try { const valid = categoryNameSchema.parse(editing ? editing.name : name); await saveCategory(valid, editing?.id); setName(""); setEditing(null); setMessage(editing ? "分類已重新命名。" : "分類已建立。" ); await load(); } catch (cause) { setError(cause instanceof Error && cause.message.startsWith("[") ? "請輸入 1 至 40 字的分類名稱。" : "分類名稱可能重複，請使用其他名稱。" ); } }
  async function setCategoryState(c: Category) { setBusy(c.id); setError(""); try { await toggleCategory(c.id, !c.is_active); setMessage(c.is_active ? "分類已停用，歷史帳目不受影響。" : "分類已啟用。" ); await load(); } catch { setError("無法更新分類。" ); } finally { setBusy(""); } }
  async function remove(c: Category) { if (!window.confirm(`刪除未使用的分類「${c.name}」？`)) return; setBusy(c.id); try { await deleteCategory(c.id); setMessage("分類已刪除。" ); await load(); } catch { setError("此分類已被帳目或常用項目使用，請改為停用。" ); } finally { setBusy(""); } }
  async function setCurrency(code: string, active: boolean) { if (code === "TWD" && !active) return; setBusy(code); try { await toggleCurrency(code, active); setMessage(active ? `${code} 已啟用。` : `${code} 已停用，歷史帳目不受影響。`); await load(); } catch { setError("無法更新幣別。" ); } finally { setBusy(""); } }
  async function submitTag(event: React.FormEvent) { event.preventDefault(); setError(""); try { const valid = tagNameSchema.parse(tagName); await saveTag(valid); setTagName(""); setMessage("Tag 已建立。" ); await load(); } catch (cause) { setError(cause instanceof Error && cause.message.startsWith("[") ? "請輸入 1 至 30 字的 Tag 名稱。" : "Tag 名稱可能重複，請使用其他名稱。" ); } }
  async function removeTag(tag: Tag) { if (!window.confirm(`刪除 Tag「${tag.name}」？帳目本身不會被刪除。`)) return; setBusy(tag.id); try { await deleteTag(tag.id); setMessage("Tag 已刪除，原帳目不受影響。" ); await load(); } catch { setError("無法刪除 Tag。" ); } finally { setBusy(""); } }
  const currencyMap = new Map(currencies.map((c) => [c.code, c]));
  if (loading) return <div className="card flex min-h-48 items-center justify-center"><LoaderCircle className="animate-spin text-moss-600" /></div>;
  return <div className="grid gap-5 lg:grid-cols-2">
    <section className="card"><h2 className="text-lg font-bold">支出分類</h2><p className="muted mt-1">完全依照你的習慣建立；使用過的分類請停用而非刪除。</p><form onSubmit={submit} className="mt-5 flex gap-2">{editing ? <input className="field" aria-label="分類名稱" value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /> : <input className="field" aria-label="新分類名稱" value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：餐飲" />}<button className="btn-primary shrink-0">{editing ? <Check size={18} /> : <Plus size={18} />}<span className="hidden sm:inline">{editing ? "儲存" : "新增"}</span></button>{editing && <button type="button" className="btn-secondary px-3" onClick={() => setEditing(null)}><X size={18} /></button>}</form><div className="mt-5 divide-y divide-stone-100">{categories.length === 0 && <p className="py-8 text-center text-stone-400">還沒有分類，先建立第一個吧</p>}{categories.map((c) => <div key={c.id} className="flex items-center gap-2 py-3"><span className={`h-2.5 w-2.5 rounded-full ${c.is_active ? "bg-moss-500" : "bg-stone-300"}`} /><span className="min-w-0 flex-1 truncate font-medium">{c.name}</span><button className="rounded-xl p-2 text-stone-400 hover:bg-stone-100" aria-label="重新命名" onClick={() => setEditing(c)}><Pencil size={17} /></button><button className="rounded-xl p-2 text-stone-400 hover:bg-red-50 hover:text-red-700" aria-label="刪除分類" disabled={busy === c.id} onClick={() => remove(c)}><Trash2 size={17} /></button><button className="btn-secondary min-h-9 px-3 py-1 text-sm" disabled={busy === c.id} onClick={() => setCategoryState(c)}>{c.is_active ? "停用" : "啟用"}</button></div>)}</div></section>
    <section className="card"><div className="flex items-center gap-2"><Tags size={20} className="text-coral" /><h2 className="text-lg font-bold">帳目 Tag</h2></div><p className="muted mt-1">Tag 是選填，可讓同一筆帳目同時擁有多個標籤。</p><form onSubmit={submitTag} className="mt-5 flex gap-2"><input className="field" aria-label="新 Tag 名稱" value={tagName} onChange={(e) => setTagName(e.target.value)} placeholder="例如：出差" maxLength={30} /><button className="btn-primary shrink-0"><Plus size={18} /><span className="hidden sm:inline">新增</span></button></form><div className="mt-5 divide-y divide-stone-100">{tags.length === 0 && <p className="py-8 text-center text-stone-400">尚未建立 Tag</p>}{tags.map((tag) => <div key={tag.id} className="flex items-center gap-3 py-3"><span className="min-w-0 flex-1 truncate font-medium">#{tag.name}</span><button className="rounded-xl p-2 text-stone-400 hover:bg-red-50 hover:text-red-700" aria-label={`刪除 Tag ${tag.name}`} disabled={busy === tag.id} onClick={() => removeTag(tag)}><Trash2 size={17} /></button></div>)}</div></section>
    <section className="card"><h2 className="text-lg font-bold">使用幣別</h2><p className="muted mt-1">記帳表單只顯示已啟用的幣別，基準幣別固定為 TWD。</p><div className="mt-5 max-h-[32rem] divide-y divide-stone-100 overflow-y-auto">{ISO_CURRENCIES.map(([code]) => { const active = code === "TWD" || currencyMap.get(code)?.is_active; return <div key={code} className="flex items-center gap-3 py-3"><span className="w-12 font-mono font-bold">{code}</span><span className="min-w-0 flex-1 text-sm text-stone-500">{CURRENCY_NAMES[code]}</span><button className={`min-h-9 rounded-full px-3 text-sm font-medium ${active ? "bg-moss-100 text-moss-700" : "bg-stone-100 text-stone-500"}`} disabled={code === "TWD" || busy === code} onClick={() => setCurrency(code, !active)}>{active ? "已啟用" : "啟用"}</button></div>; })}</div></section>
    <div className="lg:col-span-2"><StatusMessage message={error || message} error={Boolean(error)} /></div>
  </div>;
}
